name: Node CI

on: [push]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Skip CI
        uses: veggiemonk/skip-commit@master
        env:
          COMMIT_FILTER: skip ci
      - name: Prepare repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout "${GITHUB_REF:11}" --
          git remote rm origin
          git remote add origin "https://$GH_TOKEN@github.com/hipstersmoothie/bmp-ts.git"
          git fetch origin
          git branch --set-upstream-to origin/master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git remote -v
          yarn
          yarn build
          yarn lint
          yarn test
          bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
          yarn release
